export interface Unit { id: string; name: string; type: 'plant' | 'shop'; created_at: Date; }
export interface User { id: string; name: string; phone: string; password_hash: string; role: 'OWNER' | 'PLANT_MANAGER' | 'SHOP_MANAGER' | 'DRIVER'; unit_id: string | null; language: 'en' | 'mr' | 'hi'; is_active: boolean; created_at: Date; updated_at: Date; }
export interface Party { id: string; name: string; phone: string; address: string | null; village: string | null; taluka: string | null; district: string | null; pincode: string | null; gstin: string | null; is_gst_registered: boolean; credit_limit_paise: number; health_score: 'green' | 'amber' | 'red'; referred_by: string | null; notes: string | null; created_by: string; created_at: Date; updated_at: Date; deleted_at: Date | null; }
export interface Product { id: string; name: string; unit: 'brass' | 'bags' | 'pieces' | 'tonnes'; hsn_code: string | null; gst_rate: number; default_rate_paise: number; unit_id: string; is_active: boolean; created_at: Date; }
export interface Order { id: string; unit_id: string; party_id: string; order_type: 'spot' | 'delivery' | 'retail'; payment_mode: 'cash' | 'credit' | 'upi' | 'cheque' | 'neft'; status: 'pending' | 'completed' | 'cancelled'; total_paise: number; gst_total_paise: number; grand_total_paise: number; invoice_number: string | null; credit_due_date: Date | null; credit_security_type: string | null; over_limit_approved_by: string | null; created_by: string; created_at: Date; updated_at: Date; deleted_at: Date | null; }
export interface OrderItem { id: string; order_id: string; product_id: string; quantity_brass: number; quantity_kg: number | null; weighbridge_tonnes: number | null; rate_paise: number; taxable_paise: number; cgst_paise: number; sgst_paise: number; total_paise: number; }
export interface Payment { id: string; order_id: string | null; party_id: string; unit_id: string; amount_paise: number; mode: string; upi_txn_id: string | null; upi_app: string | null; cheque_number: string | null; cheque_bank: string | null; cheque_date: Date | null; cheque_is_pdc: boolean; neft_ref: string | null; received_by: string; date: Date; created_at: Date; deleted_at: Date | null; }
export interface LedgerEntry { id: string; party_id: string; order_id: string | null; payment_id: string | null; type: 'debit' | 'credit'; amount_paise: number; balance_paise: number; due_date: Date | null; status: 'current' | 'follow_up' | 'overdue' | 'critical' | 'settled'; security_type: string | null; approved_by: string; settled_at: Date | null; created_at: Date; }
export interface Trip { id: string; order_id: string; vehicle_id: string; driver_id: string; party_id: string; delivery_address_id: string | null; quantity_brass: number; weighbridge_tonnes: number | null; status: string; departed_at: Date | null; delivered_at: Date | null; fuel_litres: number | null; fuel_cost_paise: number | null; distance_km: number | null; issue_type: string | null; issue_note: string | null; delivery_photo_url: string | null; manager_note: string | null; created_by: string; created_at: Date; updated_at: Date; }
export interface StockMovement { id: string; unit_id: string; product_id: string; type: string; quantity_brass: number; reason: string | null; order_id: string | null; created_by: string; created_at: Date; }
export interface Expense { id: string; unit_id: string; category: string; description: string; amount_paise: number; payment_mode: string; date: Date; created_by: string; created_at: Date; updated_at: Date; deleted_at: Date | null; }
export interface Staff { id: string; unit_id: string; name: string; phone: string | null; role: string; salary_type: 'monthly' | 'daily'; monthly_salary_paise: number | null; daily_rate_paise: number | null; pf_deduction_paise: number; esic_deduction_paise: number; joining_date: Date; is_active: boolean; created_at: Date; }
export interface Vehicle { id: string; registration: string; type: string; capacity_brass: number; driver_id: string | null; is_active: boolean; created_at: Date; }
export interface CashClosing { id: string; unit_id: string; date: Date; opening_paise: number; received_paise: number; paid_out_paise: number; expected_closing_paise: number; actual_closing_paise: number; difference_paise: number; explanation: string | null; closed_by: string; closed_at: Date; }
export interface Invoice { id: string; order_id: string; invoice_number: string; unit_id: string; party_id: string; taxable_paise: number; cgst_paise: number; sgst_paise: number; igst_paise: number; grand_total_paise: number; amount_in_words: string; pdf_url: string | null; created_at: Date; }
export interface ApiResponse<T = any> { success: boolean; data?: T; error?: { code: string; message: string; details?: any; }; meta?: any; }
export interface PaginationParams { page: number; limit: number; sortBy?: string; sortOrder?: 'asc' | 'desc'; }
export interface AuthPayload { userId: string; role: string; unitId: string | null; }
export interface CreditAgeing { bucket: string; count: number; total_paise: number; }
export interface StaffPayroll { staff_id: string; staff_name: string; days_present: number; days_half: number; salary_earned_paise: number; advances_total_paise: number; pf_deduction_paise: number; esic_deduction_paise: number; net_payable_paise: number; }